<?xml version="1.0" encoding="utf-8"?><Database Name="Reservation_Hotel" Class="DataClasseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-VGI3O59;Initial Catalog=Reservation_Hotel;Integrated Security=True" SettingsObjectName="GestionReservationHotel.Properties.Settings" SettingsPropertyName="Reservation_HotelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Reservation" Member="Reservation">
    <Type Name="Reservation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DateReservation" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="numChambre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NomClient" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PrenomClient" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CINClient" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>