#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionReservationHotel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Reservation_Hotel")]
	public partial class DataClasseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertReservation(Reservation instance);
    partial void UpdateReservation(Reservation instance);
    partial void DeleteReservation(Reservation instance);
    #endregion
		
		public DataClasseDataContext() : 
				base(global::GestionReservationHotel.Properties.Settings.Default.Reservation_HotelConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Reservation> Reservation
		{
			get
			{
				return this.GetTable<Reservation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reservation")]
	public partial class Reservation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _DateReservation;
		
		private System.Nullable<int> _numChambre;
		
		private string _NomClient;
		
		private string _PrenomClient;
		
		private string _CINClient;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnDateReservationChanging(System.Nullable<System.DateTime> value);
    partial void OnDateReservationChanged();
    partial void OnnumChambreChanging(System.Nullable<int> value);
    partial void OnnumChambreChanged();
    partial void OnNomClientChanging(string value);
    partial void OnNomClientChanged();
    partial void OnPrenomClientChanging(string value);
    partial void OnPrenomClientChanged();
    partial void OnCINClientChanging(string value);
    partial void OnCINClientChanged();
    #endregion
		
		public Reservation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReservation", DbType="Date")]
		public System.Nullable<System.DateTime> DateReservation
		{
			get
			{
				return this._DateReservation;
			}
			set
			{
				if ((this._DateReservation != value))
				{
					this.OnDateReservationChanging(value);
					this.SendPropertyChanging();
					this._DateReservation = value;
					this.SendPropertyChanged("DateReservation");
					this.OnDateReservationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numChambre", DbType="Int")]
		public System.Nullable<int> numChambre
		{
			get
			{
				return this._numChambre;
			}
			set
			{
				if ((this._numChambre != value))
				{
					this.OnnumChambreChanging(value);
					this.SendPropertyChanging();
					this._numChambre = value;
					this.SendPropertyChanged("numChambre");
					this.OnnumChambreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomClient", DbType="VarChar(50)")]
		public string NomClient
		{
			get
			{
				return this._NomClient;
			}
			set
			{
				if ((this._NomClient != value))
				{
					this.OnNomClientChanging(value);
					this.SendPropertyChanging();
					this._NomClient = value;
					this.SendPropertyChanged("NomClient");
					this.OnNomClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrenomClient", DbType="VarChar(50)")]
		public string PrenomClient
		{
			get
			{
				return this._PrenomClient;
			}
			set
			{
				if ((this._PrenomClient != value))
				{
					this.OnPrenomClientChanging(value);
					this.SendPropertyChanging();
					this._PrenomClient = value;
					this.SendPropertyChanged("PrenomClient");
					this.OnPrenomClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CINClient", DbType="VarChar(50)")]
		public string CINClient
		{
			get
			{
				return this._CINClient;
			}
			set
			{
				if ((this._CINClient != value))
				{
					this.OnCINClientChanging(value);
					this.SendPropertyChanging();
					this._CINClient = value;
					this.SendPropertyChanged("CINClient");
					this.OnCINClientChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
